### ISSUE TITLE
Webhooks bug > Product entries are being deleted after order is placed that contain the item

### ISSUE THREAD

**Issue by austriker27** [jackabox/statamic-shopify#98] opened 2021-11-04 22:22 UTC
I finally got my webhooks working (for anyone: make sure they bypass the cloudflare firewall, if you are using CF) but they are deleting product entries after an order comes through with the item in it.

Its the weirdest thing - the products are definitely still in shopify.  What info can I provide to help debug this?

Example of a file removed: 
```md
---
id: 1ec3b324-9801-40ed-a71b-61ea586e5add
blueprint: product
product_id: 6804646035632
published_at: '2021-08-05 19:36:26'
title: 'Chunky Oversized Knit Beanie'
vendor:
  - brist-mfg
type:
  - headwear
tags:
  - beanie
options:
  option1: Color
featured_image: shopify/chunky_beanie--black.jpg
gallery:
  - shopify/chunky_beanie--black.jpg
  - shopify/chunky_beanie--charcoal.jpg
  - shopify/chunky_beanie--gray-white-speckled.jpg
  - shopify/chunky_beanie--maroon-natural.jpg
  - shopify/chunky_beanie--navy-white.jpg
  - shopify/chunky_beanie--navy.jpg
  - shopify/chunky_beanie--oatmeal.jpg
collections:
  - beanies
  - headwear
  - non-sale-items
  - popular-products
product_category:
  - headwear
published: true
---
<p>This beanie is perfect if you want a larger than life/real thick winter beanie. This oversized and chunky beanie is super soft to the touch and very comfortable. To be honest, its the best fit for for those desiring an oversized beanie or for those with bigger heads than smaller heads. Can be worn with the cuff up or down for maximum outfit matching.<br></p>
<ul>
<li>100% acrylic</li>
<li>12" knit</li>
<li>Custom RW Logo Woven Tag</li>
<li>Manufactured by a headwear company that's been making quality goods for 75+ years<br>
</li>
<li>A portion of every purchase is donated to protecting our National Parks</li>
</ul>

```

**Comment by jackabox** [comment] 2021-11-05 13:41
Hey @austriker27 have you set up the wrong endpoint here? Sounds like you're posting an order being complete to the delete product webhook rather than the update order one.

[https://statamic-shopify.jackwhiting.co.uk/CMS/webhooks]()

**Comment by austriker27** [comment] 2021-11-05 17:57
I dont think so - this looks accurate to me: 

![image](https://user-images.githubusercontent.com/14855925/140556787-435c4543-a325-4b89-8ca7-7f3784e11f20.png)

**Comment by austriker27** [comment] 2021-11-07 02:41
Im going to delete the "order creation" webhook to see if thats causing the problem. This is bad because its costing me money every time a product gets deleted.

**Comment by austriker27** [comment] 2021-12-01 13:56
This is still happening daily. Its quite fun - I have to manually check after every order to see if a product was deleted via the content update webhook.

**Comment by jackabox** [comment] 2021-12-01 13:57
Hey, @austriker27 didn't you delete the order creation webhook? Did that fix your issue? 

If it was deleted, how would the content still be deleted?

**Comment by austriker27** [comment] 2021-12-01 14:00
> Hey, @austriker27 didn't you delete the order creation webhook? Did that fix your issue?
> 
> If it was deleted, how would the content still be deleted?

No, I didnt actually delete it - because if I delete it, order quantities don't update. So I have manually find which products sold and then reimport them. Which takes more time. So I decided to leave the webhook active because either way I'm spending time but this way Im spending less time.

Its not consistently deleting all products from orders - only like probably 10%. I can share reference commits if thats helpful.

**Comment by jackabox** [comment] 2021-12-02 14:05
@austriker27 Gotcha! It's odd that it would be deleting products at all - especially odd products, as it runs the import of the single product. 

1. If you manually run the import all (from the admin/terminal) does this also delete the products?
2. is it always the same products?
3. Do you have the delete webhook also set up? Can you remove that one temporarily if so and see if that fixes your issues?

**Comment by austriker27** [comment] 2021-12-02 14:52
Thanks for the quick reply @jackabox ! Its very odd, I feel like something is out of whack between shopify and statamic.

1. I will try this and let you know - because I have so many products it usually takes many, many minutes. So I try to avoid running it. 
2. I'll create a list of products its deleting, it might be similar products. 
3. I don't have the delete webhook. I removed it in October-ish, when I was first starting to get this issue. 

Webhook screenshot: 
![image](https://user-images.githubusercontent.com/14855925/144445640-f9f7f726-a873-4f56-b34f-b41b2c0717fc.png)

**Comment by austriker27** [comment] 2021-12-02 14:53
I just noticed the `order creation` webhook has been removed from my webhooks. Ugh, I know shopify has removed it in the past when it gets an error on that route. Oh great, another thing to fix...

**Comment by jackabox** [comment] 2021-12-02 14:56
@austriker27 

Do you get a notification of the error?

If you can see which products it is, might help to work this out - my test environment I have set up seems to be stable, I can't really replicate this at the moment so will need as much information as possible.

Thanks for confirming you don't have a delete, wondered if that was being triggered weirldy.

**Comment by jackabox** [comment] 2021-12-02 15:03
> > Do you get a notification of the error?
> 
> Sorry - which error? The product getting removed? The only way I find out is by reading all the commit messages to see if files are removed. Then I have to revert those commits basically.

I meant the webhook in Shopify, sorry. When it gets removed, do you know when/why?

**Comment by austriker27** [comment] 2021-12-02 15:04
No worries! Sorry I added a bit of context by editing my earlier comment: Last time my webhooks were removed, it was because cloudflare had turned on bot attack mode on the endpoint. And apparently, per shopify support, when they don't get a 200 response they eventually remove the endpoint. And they don't tell me so there's no way of knowing I guess. I wish they would tell me!

**Comment by austriker27** [comment] 2021-12-02 15:05
Well this is weird, bot mode is turned off in my CF, so Im not sure what deleted my webhook this time: 
![image](https://user-images.githubusercontent.com/14855925/144447870-1eb8e5ca-4da3-4e73-91d7-3b78312cf290.png)

**Comment by jackabox** [comment] 2021-12-02 15:10
@austriker27 Hm, odd, maybe it was on temporarily. Unrelated on this one, if you can let me know the other things I'll see if we can dig down to why. For context, you can look in `routes/actions.php` to see what file they load and then load the class as appropriate, the only one that should be deleting is /products/delete. 

If you don't even have this endpoint though, there isn't anything else deleting it.

The only other thing that runs is `ImportSingleProductJob` which doesn't fire anything to delete a product.

**Comment by austriker27** [comment] 2021-12-03 03:05
> @austriker27 Gotcha! It's odd that it would be deleting products at all - especially odd products, as it runs the import of the single product.
> 
>     1. If you manually run the import all (from the admin/terminal) does this also delete the products?
> 
>     2. is it always the same products?
> 
>     3. Do you have the delete webhook also set up? Can you remove that one temporarily if so and see if that fixes your issues?


1. I ran import all via the admin/cp page and it didn't delete any products. 
2. 
## Products its deleted just for November, in October it was also deleting products 3-7 days a week.
### 11/26:
- content/collections/products/mrnp-sign-patch.md
- content/collections/products/hemp-slacker-beanie.md
- content/collections/products/hemp-slacker-beanie.md
### 11/25:
- content/collections/products/pride-logo-holographic-sticker.md
- content/collections/products/tahoma-badge-sticker.md
### 11/22:
- content/collections/products/the-mountains-are-for-everyone-sticker.md
### 11/20:
- content/collections/products/the-mountains-are-for-everyone-sticker.md
### 11/18:
- content/collections/products/protect-our-parks-hiking-hat.md
### 11/16:
- content/collections/products/the-mountains-are-for-everyone-sticker.md
### 11/09:
- content/collections/products/pride-logo-holographic-sticker.md
### 11/07:
- content/collections/products/neon-sunset-sticker.md
- content/collections/products/chunky-beanie.md
### 11/06:
- content/collections/products/the-mountains-are-for-everyone-sticker.md
### 11/05:
- content/collections/products/the-mountains-are-for-everyone-patch.md
- content/collections/products/the-mountains-are-for-everyone-sticker.md
### 11/04:
- content/collections/products/snow-wash-vintage-dad-hat.md
- content/collections/products/chunky-beanie.md
### 11/03:
- content/collections/products/adventure-neck-gaiter-v2.md
- content/collections/products/adventure-neck-gaiter-v2.md
- content/collections/products/chunky-beanie.md
### 11/03:
- content/collections/products/neon-sunset-waffle-beanie.md
- content/collections/products/rw-badge-eco-tee.md

3. (Mentioned this above - I dont have the delete webhook setup)

**Comment by jackabox** [comment] 2021-12-03 17:07
> I ran import all via the admin/cp page and it didn't delete any products.

This runs the same import as the webhook, so if this isn't flagging anything it'd be odd for the webhook too.

what's going on with this file `the-mountains-are-for-everyone-sticker` this seems quite a common one that's disappearing? Is there a problem with the specific files/imports, rather than the webhook as a whole? If you can import that single product again (try it several times) and see if it deletes the item

**Comment by austriker27** [comment] 2021-12-06 14:15
> This runs the same import as the webhook, so if this isn't flagging anything it'd be odd for the webhook too.

Well thats super weird. The next time the webhook deletes content on my server after an order, I'll run the import all locally to see if i can replicate products being deleted. 

Last night I just had several more products get deleted after orders were placed - its so frustrating because this means these products were unavailable to customers until I was able to check this morning and restore the products.

content/collections/products/chunky-beanie.md
content/collections/products/elevation-badge-sticker.md
content/collections/products/mrnp-dad-hat.md
content/collections/products/never-gets-old-sticker.md


> what's going on with this file the-mountains-are-for-everyone-sticker this seems quite a common one that's disappearing? Is there a problem with the specific files/imports, rather than the webhook as a whole? If you can import that single product again (try it several times) and see if it deletes the item
I'm not sure whats going on with it - I tried running the product specific import 3x via the CP page but it didn't delete it any of the times.

**Comment by jackabox** [comment] 2021-12-13 14:34
@austriker27 Hey, have you managed to try to replicate this locally? Sorry, this one is taking a while to debug as it's a bit of an odd issue that, well, shouldn't be happening (unless I'm missing something).

**Comment by austriker27** [comment] 2021-12-17 14:21
> @austriker27 Hey, have you managed to try to replicate this locally? Sorry, this one is taking a while to debug as it's a bit of an odd issue that, well, shouldn't be happening (unless I'm missing something).

Yeah its super weird for sure. I tried import all locally and it didnt work. A few days ago I noticed it deleted a product that was in an order, but then I got several more orders for the same product and it didnt get deleted. Its so odd.

**Comment by michaellindahl** [comment] 2022-01-03 03:04
@jackabox How can we help track down this issue? 

I've managed to capture the webhooks by sending them to an HTTP request bin service. _Although I've now lost the payloads as the service deleted the endpoint after 5 days. It would be great if this plugin enabled capturing the payloads and saving them to local storage._ Replaying them locally required modifying `Jackabox\Shopify\Http\Controllers\Webhooks\WebhooksController` to return `true`. Is there any additionally logging I can put in place or enable to assist in figuring out the cause of this issue?

When I attempted to playback the Order Created callback locally I got this error, which seems odd to me:
> ErrorException
> Attempt to read property "line_items" on null

Looking at the git history, there are two recent commits:

- December 31, 2021 at 9:02:53 PM PST: updated the product quantity of the-mountain-is-out-miir-camp-mug
- January 2, 2022 at 5:58:46 PM PST: updated the product quantity of the-mountain-is-out-miir-camp-mug, the-mountain-is-out-eco-tee, the-mountain-is-out-sticker, ranger-sticker. Additionally `collections/products/ranger-sticker.md` was deleted.

These two commits correlate with the two times that Shopify hit the order creation endpoint:

- Jan 3, 2022 1:53:35 AM
- Jan 1, 2022 4:57:43 AM

And hit the Product Updated endpoint multiple times.
The only difference between the two calls is the `updated_at` timestamp (Checked this on The Mountain is out Miir Camp Mug and Ranger Sticker calls).

- Jan 3, 2022 1:57:16 AM ID: Pg7RaEo7Z - The Mountain is out Miir Camp Mug
- Jan 3, 2022 1:56:40 AM ID: ZXGWRPozm - The Mountain Is Out Eco Tee
- Jan 3, 2022 1:56:40 AM ID: mNbKROJx8 - The Mountain Is Out Sticker
- Jan 3, 2022 1:56:37 AM ID: omb6RZNJ3 - Ranger Sticker
- Jan 3, 2022 1:53:32 AM ID: omb6RyJGn - The Mountain is out Miir Camp Mug
- Jan 3, 2022 1:53:30 AM ID: 1NKrwPqOw - The Mountain Is Out Sticker
- Jan 3, 2022 1:53:30 AM ID: GqGnZozYR - The Mountain Is Out Eco Tee
- Jan 3, 2022 1:53:29 AM ID: 1NKrwPqE2 - Ranger Sticker

…

- Jan 1, 2022 5:00:47 AM
- Jan 1, 2022 4:57:38 AM
- Jan 1, 2022 12:56:35 AM
- Jan 1, 2022 12:56:29 AM
- Jan 1, 2022 12:51:05 AM
- Jan 1, 2022 12:51:05 AM

**Comment by jackabox** [comment] 2022-01-06 17:36
Hey @michaellindahl.

When you've received the error on **line_items** can you log what is passed to the controller at that time?

The product quantity being updated is the correct step when these get hit by the webhook, as it's all it should update when a product is ordered. The weird part is the deletion.

As for debugging, this seems (at the current time) to only affect @austriker27's store. To tackle this we'd need to see if you can reproduce this at all, as I'm struggling to get this to replicate on my test/live stores. As for digging deeper, I can think of a few things to test:

1. If you serve a local version of the site (through a tunnel) and test the webhooks posting to it, can you replicate the delete issue happening?
2. Can you log the output when being posted to the hook before it steps through the import. This may reveal anything to us.
3. Can you try with a different Shopify store, posting to your site. You can spin a demo up for this to test it and use demo payments. 
4. If none of the above, and you're getting weird hits on the webhook, then can you send me a copy of them.
5. Double check there are no weird issues with the server and products/entries being saved causing them to delete in Statamic (such as permissions issues or other such things).

**Comment by michaellindahl** [comment] 2022-01-09 04:45
Thanks for the prompt response. 

In terms of points 1 & 2, I am having Shopify send the webhooks both to the server and to an HTTP capture bin. 
After a product was deleted on the server, I was able to replay the most recently webhooks locally (omitting any headers helped). This did not cause any deleted products locally.

Skipping to point 5, looking at the products folder on the server did highlight some inconsistent permissions. Most files are `-rw-rw-r--`. However, 11 products have the following permissions `-rw-r--r--` and one file is using `root root`. I've gone ahead and updated all files to have the same `-rw-rw-r--` permissions and owner:group. Although since the user and group are the same, I'm not sure how these permissions would have an effect on anything. We'll monitor this change and report back.

**Comment by jackabox** [comment] 2022-01-13 12:52
Hey, thanks for digging a bit deeper into this one - really weird one that I'm struggling to replicate. 

Did the products with incorrect permissions match those of the ones being deleted?

**Comment by jackabox** [comment] 2022-01-17 18:08
Hey, @michaellindahl  // @austriker27. Any further progress with this one?

**Comment by michaellindahl** [comment] 2022-01-17 18:35
@jackabox During the past couple of weeks this was happening at a frequency of once a week.

I have a feeling that the permissions got wonky, and reverting the commit that deleted the file restored the file with the correct permissions. Which is why the frequency over time decreased. Although order volume also was high during the end of the year with new product launches.

As of yet, there has not been another product deleted but we are still monitoring the situation. Due to the low order volume, I won't be confident in this assessment until we have a month of orders. We could certainly close this as being a permissions issue and if this re-occurs, we can try limiting the queue.

**Comment by michaellindahl** [comment] 2022-02-16 06:55
@jackabox this is still occurring. Sadly we already are using the `default` queue that only has one process so that is not an issue with this install. 
I'm going to try to replicate this with a new blank statamic + statamic-shopify site with the production store, where both the production site and blank site receive the same web hooks.

**Comment by jackabox** [comment] 2022-02-16 14:06
@michaellindahl Bugger, was hoping due to being quiet it had been resolved. Are you getting it on the same files – or is it a different collection of products? Let me know how the replication goes, if you can pull all the products fresh too that'd be great, as had an issue that required a fresh pull (clean set of files) to resolve recently.

**Comment by austriker27** [comment] 2022-02-16 18:37
Since my last update ([products deleted as of 11/26](https://github.com/jackabox/statamic-shopify/issues/98#issuecomment-985176701)), here's whats been deleted: 

## 02/15
content/collections/products/the-mountain-is-out-eco-tee.md

## 02/12
content/collections/products/mystery-sticker-5-pack.md

## 01/31
content/collections/products/protect-our-parks-bear-hiking-hat.md

## 01/28
content/collections/products/the-mountain-is-out-eco-tee.md
content/collections/products/rw-badge-eco-tee.md
content/collections/products/neon-sunset-sticker.md

## 01/08
content/collections/products/rainier-mountain-vinyl-decal.md

## 01/02
content/collections/products/ranger-sticker.md

## 12/28
content/collections/products/the-mountain-is-out-miir-camp-mug.md

## 12/22
content/collections/products/rw-badge-matte-black-sticker.md
content/collections/products/ranger-sticker.md

## 12/10
content/collections/products/the-mountain-is-out-eco-tee.md

## 12/05
content/collections/products/chunky-beanie.md

## 12/04
content/collections/products/elevation-badge-sticker.md
content/collections/products/mrnp-dad-hat.md
content/collections/products/never-gets-old-sticker.md

## 11/30
content/collections/products/mrnp-sign-patch.md


> Are you getting it on the same files – or is it a different collection of products?

So looks like its sometimes the same file, but not always.. which doesnt help us 😢

Hope this helps troubleshoot! 

I just ran a re-import of all the products, so maybe that will help!

**Comment by jackabox** [comment] 2022-03-02 17:08
Hey @michaellindahl Did you get chance to replicate with a fresh install?

**Comment by austriker27** [comment] 2022-04-14 14:12
> Hey @michaellindahl Did you get chance to replicate with a fresh install?

I dont think @michaellindahl has made any progress on this and I just don't have time (new baby, full time job, full time side hustle, yada yada yada). Also you will be stoked to know I dropped my headless shopify site the other day 😢 🎉 and replaced it with a shopify build. (I just dont have time or resources to fully dedicate to it). That being said I'm still going to use this awesome addon on my statamic website but just send people to the shopify hosted site on a subdomain for products.

**Comment by jackabox** [comment] 2022-05-26 12:07
Congrats @austriker27 :)

Closed for now.

**Closed** 2022-07-20 15:50 UTC
Labels: bug, help wanted, invalid
